version: "3.8"

services:
  db:
    container_name: tt-postgres-o
    image: postgres
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - tt-net

  redis:
    container_name: tt-redis-o
    image: redis
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - redisdata:/var/lib/redis/data
    networks:
      - tt-net

  backend:
    container_name: tt-backend
    restart: unless-stopped
    image: zinix/tt-backend:1.0.0
    env_file:
      - .env
    depends_on:
      - redis
      - db
    networks:
      - tt-net
    command: sh -c "pipenv run alembic upgrade head && pipenv run uvicorn main:app --reload --host 127.0.0.1 --port 8000"

  frontend:
    container_name: tt-frontend
    image: zinix/tt-frontend:1.0.1
    restart: unless-stopped
    networks:
      - tt-net

  nginx:
    container_name: tt-nginx
    restart: unless-stopped
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/fullchain.pem:/etc/nginx/fullchain.pem
      - ./nginx/privkey.key:/etc/nginx/privkey.key
    networks:
      - tt-net

networks:
  tt-net:
    name: tt-net
    driver: bridge

volumes:
  pgdata:
  redisdata:
  nginx:
