version: "3.8"

services:
  db:
    container_name: tt-postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  redis:
    container_name: tt-redis
    image: redis
    environment:
      REDIS_PORT: ${REDIS_PORT}
      REDIS_USER: ${REDIS_USER}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_DATABASES: ${REDIS_DATABASES}
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/var/lib/redis/data

volumes:
  pgdata:
  redisdata:
