version: "3.8"

services:
  db:
    container_name: tt-postgres-o
    image: postgres
    restart: always
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - tt-net
    ports:
      - "5432:5432"
  redis:
    container_name: tt-redis-o
    image: redis
    env_file:
      - .env
    restart: always
    volumes:
      - redisdata:/var/lib/redis/data
    networks:
      - tt-net
    ports:
      - "6379:6379"
  backend:
    container_name: tt-backend
    restart: always
    image: zinix/tt-backend:1.0.0
    env_file:
      - .env
    depends_on:
      - redis
      - db
    ports:
      - "8000:8000"
    networks:
      - tt-net
    command: sh -c "pipenv run alembic upgrade head && pipenv run uvicorn main:app --reload --host 0.0.0.0 --port 8000"
  frontend:
    container_name: tt-frontend
    image: zinix/tt-frontend:1.0.1
    restart: always
    networks:
      - tt-net
    ports:
      - "80:3000"
    depends_on:
      - backend

networks:
  tt-net:
    name: tt-net
    driver: bridge

volumes:
  pgdata:
  redisdata:
