version: "3.8"

services:
  db:
    container_name: tt-postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - tt-net
  redis:
    container_name: tt-redis
    image: redis
    environment:
      REDIS_PORT: ${REDIS_PORT}
      REDIS_USER: ${REDIS_USER}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_DATABASES: ${REDIS_DATABASES}
    restart: always
    volumes:
      - redisdata:/var/lib/redis/data
    networks:
      - tt-net
  backend:
    container_name: tt-backend
    restart: always
    image: zinix/tt-backend:1.0.0
    depends_on:
      - redis
      - db
    ports:
      - "8000:8000"
    networks:
      - tt-net
    command: sh -c "pipenv run alembic upgrade head && pipenv run uvicorn main:app --host 0.0.0.0 --port 8000"
  frontend:
    container_name: tt-frontend
    restart: always
    image: zinix/tt-frontend:1.0.1
    depends_on:
      - backend
    ports:
      - "80:3000"
    networks:
      - tt-net

networks:
  tt-net:
    name: tt-net
    driver: bridge

volumes:
  pgdata:
  redisdata:
