"""init

Revision ID: 82a9544d92c1
Revises: 
Create Date: 2024-09-15 17:18:24.931020

"""
from typing import Sequence, Union
from argon2 import PasswordHasher
from sqlalchemy.orm import sessionmaker
from alembic import op
import fastapi_users_db_sqlalchemy
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from models import UserModel
from utils.env.get_env_variables import EnvironmentVariables

# revision identifiers, used by Alembic.
revision: str = '82a9544d92c1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

Session = sessionmaker(bind=op.get_bind())

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('nickname', sa.String(), nullable=True),
    sa.Column('permissions', sa.SMALLINT(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('surname', sa.String(), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=1024), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nickname')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('identifier', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('description_full', sa.String(), nullable=True),
    sa.Column('description_short', sa.String(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'identifier'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('identifier')
    )
    op.create_table('attempt_stats',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('stats', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('percent', sa.Float(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('questions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('question_body', sa.String(), nullable=False),
    sa.Column('order', sa.SMALLINT(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('answers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('user_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('summary_attempt_stats',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('best_percent', sa.Float(), nullable=False),
    sa.Column('avg_percent', sa.Float(), nullable=False),
    sa.Column('attempt_amount', sa.Float(), nullable=False),
    sa.Column('resulting_attempt', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['resulting_attempt'], ['attempt_stats.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    ph: PasswordHasher = PasswordHasher()
    session = Session()
    superuser = UserModel(email=EnvironmentVariables.SUPERUSER_LOGIN.value,
                          hashed_password=ph.hash(EnvironmentVariables.SUPERUSER_PASSWORD.value),
                          permissions=0,
                          is_superuser=True)
    session.add(superuser)
    test_user = UserModel(email=EnvironmentVariables.TEST_USER.value,
                          hashed_password=ph.hash(EnvironmentVariables.TEST_USER_PASSWORD.value),
                          permissions=0)
    session.add(test_user)
    session.commit()
    session.close()
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('summary_attempt_stats')
    op.drop_table('answers')
    op.drop_table('questions')
    op.drop_table('attempt_stats')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
