from services.router_logic.task.add import *
from services.router_logic.task.delete_by_id import *
from services.router_logic.task.get_by_id_to_observe import *
from services.router_logic.task.get_by_id_to_solve import *
from services.router_logic.task.task_get_by_id_without_questions import *
from services.router_logic.task.get_by_title import *
from services.router_logic.task.get_by_user import *
from services.router_logic.task.get_many import *
from services.router_logic.task.patch import *
from services.router_logic.task.download_file import *
